# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-01 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_usercheckin_deleted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='deleted_at',
            new_name='deleted',
        ),
    ]
