# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-01 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180401_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='permanent',
            field=models.BooleanField(default=False),
        ),
    ]
