# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-01 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_event_permanent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
